#!/bin/sh
# uam -- pmount helper script
# (c) 2008-2011 Michał Górny
# Released under the terms of the 3-clause BSD license

LIBDIR=$(dirname "${0}")

. "${LIBDIR}"/uam-common.sh

get_mountpoint() {
	local _mp mp mpdev
	_mp=${1}

	[ -z "${_mp}" ] && return 0
	mp=${MOUNTPOINT_BASE}/${_mp%%/}
	mpdev=$(mp_used "${mp}")

	if [ -z "${mpdev}" ]; then
		MOUNTPOINT=${_mp%%/}
		return 1
	fi

	return 0
}

DEVPATH=${1}

if [ -z "${DEVPATH}" ]; then
	outmsg "No device supplied."
	exit 1
fi

conf_read TRACE=
if ! env_populate "${HOOK_PMOUNT_CACHE}"; then
	outmsg "Unable to get device information."
	exit 1
fi

conf_read TRACE= VERBOSE=1

hook_exec pre-mount

MOUNTPOINT=
foreach MOUNTPOINT_TEMPLATES get_mountpoint

if [ -n "${MOUNTPOINT}" ]; then
	pmount "${DEVPATH}" "${MOUNTPOINT}"
else
	pmount "${DEVPATH}"
fi

RET=${?}
if [ ${RET} -eq 0 ]; then
	hook_exec post-mount
else
	hook_exec mount-failed
fi

exit ${RET}
