#!/bin/sh
# uam -- pmount helper script
# (c) 2008-2011 Michał Górny
# Released under the terms of the 3-clause BSD license

LIBDIR=$(dirname "${0}")

. "${LIBDIR}"/uam-common.sh

unset DEVNAME DEVPATH

find_devpath() {
	local x hadargterm
	hadargterm=

	for x; do
		case "${x}" in
			--)
				hadargterm=1
				continue
				;;
			-*)
				# Ignore pmount args
				[ -n "${hadargterm}" ] || continue
				;;
		esac

		DEVPATH=${x}
		break
	done
}

find_devpath "${@}"

if [ -z "${DEVPATH}" ]; then
	pumount "${@}"
	exit ${?}
fi

mp=$(mp_find "${DEVPATH}")
conf_read TRACE=

debug "Running uam-pumount on ${DEVPATH}."

hook_exec pre-umount

if [ -n "${mp}" ]; then
	debug "... found ${DEVPATH} mounted in ${mp}, trying to umount."

	pumount "${@}"

	RET=${?}
	if [ ${RET} -eq 0 ]; then
		debug "...... pumount successful."
		summary "unmounted sucessfully."
	else
		debug "...... unable to pumount device."
		summary "pumount failed."
	fi
	hook_exec post-umount
else
	summary "is not mounted."
	debug "... not mounted."
fi

exit ${RET}
